DROP TABLE IF EXISTS notes_labels;
DROP TABLE IF EXISTS notes_items;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS color;
DROP TYPE IF EXISTS note_type;
